version: "2"

services:
  nginx:
    mem_limit: 26214400
    image: 568063086568.dkr.ecr.eu-west-1.amazonaws.com/lbv-nginx:latest
    ports:
      - "80:80"
    links:
      - node
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "lbv"
        awslogs-stream-prefix: "nginx"

  node:
    image: 568063086568.dkr.ecr.eu-west-1.amazonaws.com/lbv-node:latest
    mem_limit: 52428800
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "lbv"
        awslogs-stream-prefix: "node"
    environment:
      NODE_ENV: production
